name: Swift Lint

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 lint:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3

   - name: Install SwiftLint
     run: |
       sudo apt-get update
       sudo apt-get install swiftlint

   - name: Run SwiftLint
     run: swiftlint lint --strict
