# .swiftlint.yml
included:
  - Sources
excluded:
  - Tests
  - .build
disabled_rules:
  - trailing_whitespace
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - force_cast
  - force_try
  - cyclomatic_complexity 
  - nesting
  - multiple_closures_with_trailing_closure
  - todo
  - type_name
line_length:
  warning: 120
  error: 200
opt_in_rules:
  - empty_count
  - missing_docs